

const datos = {
    peliculas: [
      {
        id: "1",
        titulo: "El Padrino",
        director: "Francis Ford Coppola",
        anio: 1972,
        poster: "../librerias/img/peli.png",
        genero: ["Drama", "Crimen"],
        duracion: 175,
        reparto: ["Marlon Brando", "Al Pacino", "James Caan"],
        sinopsis:
          "El patriarca de una familia de la mafia transferirá el control de su imperio a su hijo menor.",
      },
      {
        id: "2",
        titulo: "El Señor de los Anillos: La Comunidad del Anillo",
        director: "Peter Jackson",
        anio: 2001,
        poster: "../librerias/img/peli.png",
        genero: ["Fantasía", "Aventuras"],
        duracion: 178,
        reparto: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
        sinopsis:
          "Un hobbit se une a un grupo de seres para destruir un anillo mágico y evitar que caiga en manos del malvado Sauron.",
      },
      {
        id: "3",
        titulo: "La Lista de Schindler",
        director: "Steven Spielberg",
        anio: 1993,
        poster: "../librerias/img/peli.png",
        genero: ["Drama", "Historia"],
        duracion: 195,
        reparto: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
        sinopsis:
          "Un empresario alemán salva a más de mil judíos durante el Holocausto.",
      },
      {
        id: "4",
        titulo: "Forrest Gump",
        director: "Robert Zemeckis",
        anio: 1994,
        poster: "../librerias/img/peli.png",
        genero: ["Drama", "Comedia"],
        duracion: 142,
        reparto: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        sinopsis:
          "Un hombre con discapacidad intelectual vive una vida llena de aventuras y conoce a algunas de las personas más importantes de la historia estadounidense.",
      },
      {
        id: "5",
        titulo: "El Padrino: Parte II",
        director: "Francis Ford Coppola",
        anio: 1974,
        poster: "../librerias/img/peli.png",
        genero: ["Drama", "Crimen"],
        duracion: 202,
        reparto: ["Al Pacino", "Robert De Niro", "Robert Duvall"],
        sinopsis:
          "Un joven Vito Corleone comienza su ascenso al poder en la mafia mientras Michael Corleone intenta expandir el imperio de la familia.",
      },
      {
        id: "6",
        titulo: "El Caballero de la Noche",
        director: "Christopher Nolan",
        anio: 2008,
        poster: "../librerias/img/peli.png",
        genero: ["Acción", "Crimen"],
        duracion: 152,
        reparto: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        sinopsis:
          "Batman se enfrenta a uno de sus villanos más peligrosos, el Joker, en una lucha por el alma de Gotham City.",
      },
      {
        id: "7",
        titulo: "La Vida es Bella",
        director: "Roberto Benigni",
        anio: 1997,
        poster: "../librerias/img/peli.png",
        genero: ["Drama", "Comedia"],
        duracion: 116,
        reparto: ["Roberto Benigni", "Nicoletta Braschi", "Giorgio Cantarini"],
        sinopsis:
          "Un hombre italiano utiliza su ingenio y su amor por su hijo para protegerlo durante su encarcelamiento en un campo de concentración nazi.",
      },
      {
        id: "8",
        titulo: "Origen",
        director: "Christopher Nolan",
        anio: 2010,
        poster: "../librerias/img/peli.png",
        genero: ["Acción", "Ciencia ficción"],
        duracion: 148,
        reparto: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
        sinopsis:
          "Un grupo de especialistas en sueños es contratado para realizar un acto de manipulación de sueños en una persona poderosa para cambiar el curso de la historia.",
      },
      {
        id: "9",
        titulo: "Star Wars: Episodio IV - Una Nueva Esperanza",
        director: "George Lucas",
        anio: 1977,
        poster: "../librerias/img/peli.png",
        genero: ["Ciencia ficción", "Acción"],
        duracion: 121,
        reparto: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
        sinopsis:
          "Un joven granjero se une a una princesa y un contrabandista para luchar contra el Imperio Galáctico y destruir la Estrella de la Muerte.",
      },
      {
        id: "10",
        titulo: "Pulp Fiction",
        director: "Quentin Tarantino",
        anio: 1994,
        poster: "../librerias/img/peli.png",
        genero: ["Crimen", "Drama"],
        duracion: 154,
        reparto: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
        sinopsis:
          "Una serie de historias interconectadas sobre criminales, asesinos y otros personajes marginales en Los Ángeles.",
      },
      {
        id: "11",
        titulo: "El Silencio de los Inocentes",
        director: "Jonathan Demme",
        anio: 1991,
        poster: "../librerias/img/peli.png",
        genero: ["Crimen", "Drama"],
        duracion: 118,
        reparto: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
        sinopsis:
          "Una joven agente del FBI busca la ayuda de un asesino en serie encarcelado para dar caza a otro asesino en serie que aún está activo.",
      },
      {
        id: "12",
        titulo: "El Rey León",
        director: "Roger Allers, Rob Minkoff",
        anio: 1994,
        poster: "../librerias/img/peli.png",
        genero: ["Animación", "Aventuras"],
        duracion: 88,
        reparto: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
        sinopsis:
          "Un joven león debe enfrentar a su malvado tío para reclamar su lugar como rey de la selva africana.",
      },
      {
        id: "13",
        titulo: "El Club de la Pelea",
        director: "David Fincher",
        anio: 1999,
        poster: "../librerias/img/peli.png",
        genero: ["Drama", "Crimen"],
        duracion: 139,
        reparto: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
        sinopsis:
          "Un hombre insomne se une a un grupo clandestino de lucha libre para encontrar un sentido a su vida, pero las cosas se complican cuando su amigo imaginario se convierte en un peligroso líder anarquista.",
      },
      {
        id: "14",
        titulo: "El Gran Hotel Budapest",
        director: "Wes Anderson",
        anio: 2014,
        poster: "../librerias/img/peli.png",
        genero: ["Comedia", "Aventuras"],
        duracion: 100,
        reparto: ["Ralph Fiennes", "Tony Revolori", "F. Murray Abraham"],
        sinopsis:
          "Las aventuras de un legendario conserje de un famoso hotel europeo y su joven protegido, quienes se ven envueltos en el robo de una pintura valiosa y la batalla por una gran fortuna familiar.",
      },
      {
        id: "15",
        titulo: "Titanic",
        director: "James Cameron",
        anio: 1997,
        poster: "../librerias/img/peli.png",
        genero: ["Drama", "Romance"],
        duracion: 194,
        reparto: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
        sinopsis:
          "Un joven artista y una joven aristócrata se enamoran mientras viajan en el Titanic en su fatídico viaje inaugural.",
      },
      {
        id: "16",
        titulo: "Matrix",
        director: "The Wachowskis",
        anio: 1999,
        poster: "../librerias/img/peli.png",
        genero: ["Acción", "Ciencia ficción"],
        duracion: 136,
        reparto: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        sinopsis:
          "Un programador de computadoras descubre que el mundo en el que vive es una simulación y se une a un grupo de rebeldes para luchar contra las máquinas que lo controlan.",
      },
    ],
  };